[project]
name = "cdaf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chat-downloader>=0.2.8",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "nbconvert>=7.17.1",
    "opencv-python-headless>=4.13.0.92",
    "pandas>=3.0.2",
    "pip>=26.1",
    "pytesseract>=0.3.13",
    "seaborn>=0.13.2",
    "yt-dlp>=2026.3.17",
]
